REQUIRED_SCHEMAS = ("app", "audit", "bronze", "gold", "silver")

REQUIRED_TABLES = {
    "app": (
        "accounts",
        "audit_logs",
        "categories",
        "categorization_rules",
        "goals",
        "institutions",
        "purchase_decisions",
        "reference_options",
        "settings",
    ),
    "bronze": (
        "import_batches",
        "parser_errors",
        "raw_csv_rows",
        "raw_file_metadata",
        "raw_files",
        "raw_pdf_pages",
        "raw_pdf_text",
        "raw_sheet_data",
        "raw_xlsx_rows",
    ),
    "gold": (
        "financial_alerts",
        "future_commitments",
        "goal_100k_progress",
        "passive_income_monthly",
        "portfolio_allocation",
        "purchase_decision_context",
        "reserve_status",
    ),
    "silver": (
        "accounts",
        "card_invoices",
        "card_transactions",
        "cards",
        "cash_transactions",
        "installments",
        "investment_assets",
        "investment_income",
        "investment_positions",
        "investment_trades",
        "investment_transactions",
        "manual_investment_positions",
        "payroll_deductions",
        "payroll_earnings",
        "payroll_items",
        "payroll_statements",
        "pension_positions",
        "purchase_decisions",
    ),
}

REQUIRED_COLUMNS = {
    ("bronze", "raw_files"): (
        "id",
        "original_filename",
        "stored_path",
        "sha256_hash",
        "status",
        "metadata",
    ),
    ("bronze", "import_batches"): (
        "id",
        "raw_file_id",
        "source_type",
        "status",
        "parser_name",
    ),
    ("silver", "cash_transactions"): (
        "id",
        "account_id",
        "transaction_date",
        "amount",
        "source_file_id",
        "import_batch_id",
        "raw_reference",
        "confidence_score",
        "needs_review",
        "review_status",
    ),
    ("silver", "investment_positions"): (
        "id",
        "asset_id",
        "reference_date",
        "gross_value",
        "net_value",
        "counts_as_reserve",
        "source_file_id",
        "import_batch_id",
    ),
    ("gold", "reserve_status"): (
        "id",
        "reference_date",
        "avg_monthly_expenses_3m",
        "reserve_target",
        "eligible_reserve_amount",
        "gap_amount",
        "status",
    ),
    ("gold", "purchase_decision_context"): (
        "id",
        "reference_date",
        "minimum_monthly_contribution",
        "reserve_target",
        "invested_amount",
        "available_after_commitments",
    ),
    ("app", "audit_logs"): (
        "id",
        "entity_schema",
        "entity_table",
        "entity_id",
        "action",
        "created_at",
    ),
    ("app", "categorization_rules"): (
        "id",
        "pattern",
        "match_type",
        "category_id",
        "priority",
        "confidence_score",
        "is_active",
    ),
    ("app", "reference_options"): (
        "id",
        "option_group",
        "option_key",
        "label",
        "is_active",
    ),
    ("silver", "cards"): (
        "id",
        "institution",
        "institution_id",
        "card_name",
        "brand",
        "brand_id",
        "last_four_digits",
        "is_virtual",
        "is_active",
    ),
    ("silver", "manual_investment_positions"): (
        "id",
        "institution",
        "product_name",
        "product_id",
        "asset_class",
        "gross_value",
        "counts_as_reserve",
        "rate_type",
        "rate_index",
        "liquidity_type",
    ),
}
